[package]
name = "dotilim"
version = "1.0.0"
authors = ["Selwyn <talk@selwyn.cc>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
dirs = "3.0"
glob = "0.3"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
shellexpand = "2.0"
toml = "0.5"
